<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function getTopLikedPost()
    {
        return $this->getEntityManager()
                ->getRepository('AppBundle:Post')
                ->createQueryBuilder('p')
                ->orderBy('p.like', 'DESC')
                ->getQuery()
                ->getResult();
    }

    public function getTopDislikedPost()
    {
        return $this->getEntityManager()
            ->getRepository('AppBundle:Post')
            ->createQueryBuilder('p')
            ->orderBy('p.dislike', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
