<?php
namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeRepository extends EntityRepository
{
    public function getTopPopularTheme()
    {
        $themes = $this->getEntityManager()
                    ->getRepository('AppBundle:Theme')
                    ->createQueryBuilder('t')
                    ->groupBy('t.convertedName')
                    ->setMaxResults(10)
                    ->getQuery()
                    ->getResult();

        usort($themes, function ($a, $b) {
            if (COUNT($a->getPosts()) == COUNT($b->getPosts())) {
                return 0;
            }

            return (COUNT($a->getPosts()) > COUNT($b->getPosts())) ? -1 : 1;
        });

        return $themes;
    }
}
